// Code generated by "stringer -type=NakamaMessage"; DO NOT EDIT.

package guard

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GetAccount-0]
	_ = x[UpdateAccount-1]
	_ = x[SessionRefresh-2]
	_ = x[AuthenticateApple-3]
	_ = x[AuthenticateCustom-4]
	_ = x[AuthenticateDevice-5]
	_ = x[AuthenticateEmail-6]
	_ = x[AuthenticateFacebook-7]
	_ = x[AuthenticateFacebookInstantGame-8]
	_ = x[AuthenticateGameCenter-9]
	_ = x[AuthenticateGoogle-10]
	_ = x[AuthenticateSteam-11]
	_ = x[ListChannelMessages-12]
	_ = x[ListFriends-13]
	_ = x[AddFriends-14]
	_ = x[DeleteFriends-15]
	_ = x[BlockFriends-16]
	_ = x[ImportFacebookFriends-17]
	_ = x[CreateGroup-18]
	_ = x[UpdateGroup-19]
	_ = x[DeleteGroup-20]
	_ = x[JoinGroup-21]
	_ = x[LeaveGroup-22]
	_ = x[AddGroupUsers-23]
	_ = x[BanGroupUsers-24]
	_ = x[KickGroupUsers-25]
	_ = x[PromoteGroupUsers-26]
	_ = x[DemoteGroupUsers-27]
	_ = x[ListGroupUsers-28]
	_ = x[ListUserGroups-29]
	_ = x[ListGroups-30]
	_ = x[DeleteLeaderboardRecord-31]
	_ = x[ListLeaderboardRecords-32]
	_ = x[WriteLeaderboardRecord-33]
	_ = x[ListLeaderboardRecordsAroundOwner-34]
	_ = x[LinkApple-35]
	_ = x[LinkCustom-36]
	_ = x[LinkDevice-37]
	_ = x[LinkEmail-38]
	_ = x[LinkFacebook-39]
	_ = x[LinkFacebookInstantGame-40]
	_ = x[LinkGameCenter-41]
	_ = x[LinkGoogle-42]
	_ = x[LinkSteam-43]
	_ = x[ListMatches-44]
	_ = x[ListNotifications-45]
	_ = x[DeleteNotifications-46]
	_ = x[ListStorageObjects-47]
	_ = x[ReadStorageObjects-48]
	_ = x[WriteStorageObjects-49]
	_ = x[DeleteStorageObjects-50]
	_ = x[JoinTournament-51]
	_ = x[ListTournamentRecords-52]
	_ = x[ListTournaments-53]
	_ = x[WriteTournamentRecord-54]
	_ = x[ListTournamentRecordsAroundOwner-55]
	_ = x[UnlinkApple-56]
	_ = x[UnlinkCustom-57]
	_ = x[UnlinkDevice-58]
	_ = x[UnlinkEmail-59]
	_ = x[UnlinkFacebook-60]
	_ = x[UnlinkFacebookInstantGame-61]
	_ = x[UnlinkGameCenter-62]
	_ = x[UnlinkGoogle-63]
	_ = x[UnlinkSteam-64]
	_ = x[GetUsers-65]
}

const _NakamaMessage_name = "GetAccountUpdateAccountSessionRefreshAuthenticateAppleAuthenticateCustomAuthenticateDeviceAuthenticateEmailAuthenticateFacebookAuthenticateFacebookInstantGameAuthenticateGameCenterAuthenticateGoogleAuthenticateSteamListChannelMessagesListFriendsAddFriendsDeleteFriendsBlockFriendsImportFacebookFriendsCreateGroupUpdateGroupDeleteGroupJoinGroupLeaveGroupAddGroupUsersBanGroupUsersKickGroupUsersPromoteGroupUsersDemoteGroupUsersListGroupUsersListUserGroupsListGroupsDeleteLeaderboardRecordListLeaderboardRecordsWriteLeaderboardRecordListLeaderboardRecordsAroundOwnerLinkAppleLinkCustomLinkDeviceLinkEmailLinkFacebookLinkFacebookInstantGameLinkGameCenterLinkGoogleLinkSteamListMatchesListNotificationsDeleteNotificationsListStorageObjectsReadStorageObjectsWriteStorageObjectsDeleteStorageObjectsJoinTournamentListTournamentRecordsListTournamentsWriteTournamentRecordListTournamentRecordsAroundOwnerUnlinkAppleUnlinkCustomUnlinkDeviceUnlinkEmailUnlinkFacebookUnlinkFacebookInstantGameUnlinkGameCenterUnlinkGoogleUnlinkSteamGetUsers"

var _NakamaMessage_index = [...]uint16{0, 10, 23, 37, 54, 72, 90, 107, 127, 158, 180, 198, 215, 234, 245, 255, 268, 280, 301, 312, 323, 334, 343, 353, 366, 379, 393, 410, 426, 440, 454, 464, 487, 509, 531, 564, 573, 583, 593, 602, 614, 637, 651, 661, 670, 681, 698, 717, 735, 753, 772, 792, 806, 827, 842, 863, 895, 906, 918, 930, 941, 955, 980, 996, 1008, 1019, 1027}

func (i NakamaMessage) String() string {
	if i < 0 || i >= NakamaMessage(len(_NakamaMessage_index)-1) {
		return "NakamaMessage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NakamaMessage_name[_NakamaMessage_index[i]:_NakamaMessage_index[i+1]]
}
